In [1]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from 'c:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [11]:
#Create difference tensors
string = tf.Variable("This is String", tf.string)
int = tf.Variable(1515, tf.int16)
float = tf.Variable(48.6566, tf.float64)

# with high degree/rank
rank1_tensor = tf.Variable(["apple", "orange", "pineapple"], tf.string)
rank2_tensor = tf.Variable([["apple", "orange", "pineapple"],["A", "B", "C"]], tf.string)
rank3_tensor = tf.Variable([["apple", "orange", "pineapple"],["A", "B", "C"],["E", "F", "G"]], tf.string)

print(tf.rank(rank1_tensor))
print(tf.rank(rank2_tensor))
print(tf.rank(rank3_tensor))

#shape of tensor(amount of elements that exist in each dimension)
print(rank2_tensor.shape)
print(rank3_tensor.shape)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
(2, 3)
(3, 3)


In [13]:
#change the shape of tensor
tensor1 = tf.ones([1, 2, 3])  # element "1", raws "2", columns "3" 
tensor2 = tf.reshape(tensor1, [2, 3, 1])
tensor3 = tf.reshape(tensor2, [3, -1])

print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
